#!/usr/bin/env python3
"""Extract the original's HESTRNGS table from the user's installation.

    python tools/hestrings_extract.py
    python tools/hestrings_extract.py --lang de --lbx /path/to/HGSTRNGS.LBX

**THE HELP-TEXT PATTERN** (decision 38): the bytes are moved out
untouched, `core/hestrings.py` decodes at load time, the file carries a
format version and is never committed, and `setup.py` names this
command when it is absent.

**THE SAME ENTRY SHAPE AS ESTRINGS.** `Load_H_Strings_` (harold.cpp:
1515-1590) loads entry 0 through `Farload_Data_Static_`
(farload.cpp:215), which reads the entry's own 4-byte
(total_count, element_size) header and the block after it — so the
block starts at offset 4 — and walks it `strlen + 1` per string for
397 strings, an empty string being a valid entry. The walk here is
`estrings_extract.split_block` with the count changed, imported rather
than copied.

**GENERATED, NEVER COMMITTED** (decisions 38, 40, 42) — it is the
user's game data.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core import lbx  # noqa: E402
from core.config import BASE_DIR, load_settings  # noqa: E402
from core.hestrings import (  # noqa: E402
    FORMAT_VERSION, HSTRINGS_COUNT, LANGUAGE_FILES, string_file)
import estrings_extract  # noqa: E402

GAME_DIR = os.path.expanduser("~/Master of Orion 2")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lbx", default=None)
    parser.add_argument("--lang", default=None,
                        help="language code; default: settings.json")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    lang = args.lang or load_settings().get("language", "en")
    if lang not in LANGUAGE_FILES:
        sys.exit(f"unknown language {lang!r}; known: "
                 f"{sorted(LANGUAGE_FILES)}")
    path = args.lbx or os.path.join(GAME_DIR, LANGUAGE_FILES[lang])
    if not os.path.exists(path):
        sys.exit(f"{path} not found. Point --lbx at your own "
                 f"installation's {LANGUAGE_FILES[lang]}.")

    blob = lbx.read_entry(path, 0)
    total_count, element_size = estrings_extract.read_header(blob)
    raw = estrings_extract.split_block(blob, HSTRINGS_COUNT)
    if len(raw) != HSTRINGS_COUNT:
        sys.exit(f"{path}: the block holds {len(raw)} strings and the "
                 f"original walks {HSTRINGS_COUNT} (harold.cpp:1583)")
    strings = [estrings_extract.decode(r) for r in raw]
    out = args.out or os.path.join(BASE_DIR, *string_file(lang).split("/"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    doc = {
        "_comment": "Generated by tools/hestrings_extract.py from the "
                    "player's own " + LANGUAGE_FILES[lang] + ". Never "
                    "committed (decision 38).",
        "_source": "harold.cpp:1515-1590",
        "language": lang,
        "format": FORMAT_VERSION,
        "header": {"total_count": total_count,
                   "element_size": element_size},
        "strings": strings,
    }
    with open(out, "w", encoding="utf-8") as handle:
        json.dump(doc, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print(f"{len(strings)} strings -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
