#!/usr/bin/env python3
"""Extract the Info screen's own texts from the player's MOO2 — work order 175 D.

    python tools/infotext_extract.py                # English, the usual dir
    python tools/infotext_extract.py --lang de --dir /path/to/'Master of Orion 2'

Writes `assets/shared/names/infotext_<lang>.json` (decision 38's shape: the
bytes out untouched, a format version, never committed, its absence a
state the screen explains). Three sources the other extractors do not
read, each traced to the line that loads it:

  topics   HELP.LBX entries 1-16 (`<lang>_HELP.LBX` for the others,
           textbox.cpp:17-36): `s_help_topic_record {char text[80]; u32
           id}` (orion2.h:1016) behind the usual 4-byte (count, size)
           header. 1-14 are the Reference categories' topic lists
           (info.cpp:1018-1050), 15 the "How to?" topics (:1829-1839), 16
           a list the screen does not show. Kept in the file's order — the
           screen sorts a category the way info.cpp:1033-1046 does.
  traits   RACESTUF.LBX entry 8 + language, one NUL-separated block walked
           by `Load_Player_Special_Names_` (loader.cpp:104-128) into 32
           `_special_ability_names` — the Race Statistics page's trait
           names (info.cpp:338-404)
  groups   BILLTEX2.LBX, `Get_Text_Message_`'s shape (message * 6 + language,
           jim.cpp:336-359): the Tech Review's group headers
           (info.cpp:1516) — 0..25
"""
import argparse
import json
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from core import infotext, lbx  # noqa: E402
from core.config import load_settings  # noqa: E402

LANGUAGES = {"en": 0, "de": 1, "fr": 2, "es": 3, "it": 4}
HELP_FILE = {"en": "HELP.LBX", "de": "GER_HELP.LBX", "fr": "FRE_HELP.LBX",
             "es": "SPA_HELP.LBX", "it": "ITA_HELP.LBX"}
TOPIC_ENTRIES = range(1, 17)
TOPIC_TEXT, TOPIC_SIZE = 80, 84
RACESTUF_FIRST, TRAIT_NAMES = 8, 32
GROUPS = 26
DEFAULT_DIR = os.path.expanduser("~/Master of Orion 2")


def _find(folder, name):
    want = name.lower()
    for f in os.listdir(folder):
        if f.lower() == want:
            return os.path.join(folder, f)
    return None


def decode(raw):
    return raw.split(b"\x00")[0].decode("cp437", errors="replace")


def topics(blob):
    """[(text, id)] of one topic-list entry."""
    count, size = struct.unpack_from("<HH", blob, 0)
    if size != TOPIC_SIZE:
        raise lbx.LbxError(f"topic record size {size}, not {TOPIC_SIZE}")
    out = []
    for k in range(count):
        at = 4 + k * size
        out.append((decode(blob[at:at + TOPIC_TEXT]),
                    struct.unpack_from("<I", blob, at + TOPIC_TEXT)[0]))
    return out


def trait_names(blob):
    """`Load_Player_Special_Names_`'s walk: skip to the next NUL, then over
    every NUL — a run of them is ONE separator (loader.cpp:115-124)."""
    names, offset = [], 0
    while len(names) < TRAIT_NAMES and offset < len(blob):
        end = blob.find(b"\x00", offset)
        end = len(blob) if end < 0 else end
        names.append(blob[offset:end].decode("cp437", errors="replace"))
        while end < len(blob) and blob[end] == 0:
            end += 1
        offset = end
    return names


def group_names(path, slot):
    import billtext_extract as bt
    total = bt.entry_count(path)
    out = {}
    for m in range(GROUPS):
        index = m * 6 + slot
        if index >= total:
            break
        text, problem = bt.read_message(lbx.read_entry(path, index))
        if text is not None and not problem:
            out[str(m)] = text
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dir", default=DEFAULT_DIR)
    ap.add_argument("--lang", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    lang = args.lang or load_settings().get("language", "en")
    if lang not in LANGUAGES:
        sys.exit(f"unknown language {lang!r}; known: {sorted(LANGUAGES)}")
    paths = {n: _find(args.dir, n) for n in
             (HELP_FILE[lang], "RACESTUF.LBX", "BILLTEX2.LBX")}
    missing = [n for n, p in paths.items() if p is None]
    if missing:
        sys.exit(f"{missing} not found in {args.dir}. Point --dir at your "
                 f"own installation.")
    help_entries = lbx.read_entries(paths[HELP_FILE[lang]])
    racestuf = lbx.read_entries(paths["RACESTUF.LBX"])
    data = {
        "_comment": ("GENERATED by tools/infotext_extract.py from the "
                     "player's own HELP, RACESTUF and BILLTEX2 files. Derived "
                     "from the user's own MOO2 installation — do not edit, "
                     "do not ship."),
        "language": lang,
        "format": infotext.FORMAT_VERSION,
        "topics": {str(e): [list(t) for t in topics(help_entries[e])]
                   for e in TOPIC_ENTRIES if e < len(help_entries)},
        "traits": trait_names(racestuf[RACESTUF_FIRST + LANGUAGES[lang]]),
        "groups": group_names(paths["BILLTEX2.LBX"], LANGUAGES[lang]),
    }
    out_dir = args.out or os.path.join(ROOT, "assets", "shared", "names")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, os.path.basename(infotext.text_file(lang)))
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    print(f"wrote {path}: {sum(len(v) for v in data['topics'].values())} "
          f"topics in {len(data['topics'])} lists, {len(data['traits'])} "
          f"trait names, {len(data['groups'])} group names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
