#!/usr/bin/env python3
"""The weapon firing-arc words, out of the player's own KENTEXT.LBX.

**THE HELP-TEXT PATTERN** (decision 38), after the help texts, the
building names, ESTRINGS and HESTRNGS: the strings are not in the
orion2re source but in the player's installation, so this moves the
bytes out untouched and `core/kentext.py` decodes at load time. Never
committed; `tools/setup.py` reports it absent.

**THE ADDRESSING IS THE THING THIS FILE EXISTS TO RECORD.**
`JIM::Get_Text_Message_(file, message_index, dest, max_len)`
(jim.cpp) does

    Farload_Data_Static_(file, message_index * 6 + language, buffer,
                         0, 1, sizeof(buffer))

— **six LBX entries per message, one per language**, with the language
clamped to 0..5. So message 3 is entry 18 in English and entry 19 in
German, and reading "entry 3" gives an unrelated string, which is what
it looked like before the call was read properly. Each entry opens with
the same 4-byte (count, element_size) header every `Farload_Data_Static_`
block has, and the string is NUL-terminated inside the 100 bytes after
it.

`KEN::Ken_Get_Text_Message_` (ken.cpp) splits the table in two: index
>= 0x50 goes to KENTEXT1.LBX at index - 0x50, below it to KENTEXT.LBX.
Only the low table is needed here.

The four words this takes are `DESIGN::Weapon_Arc_String_`'s
(design.cpp), which tests the arc bits in order and answers with
message 3, 4, 6 or 5 — and, for 0x10, with the **literal "360"**, which
is in the engine and not in any table, so it is transcribed in
`core/kentext.py` rather than read here.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core import lbx                                      # noqa: E402
from core.kentext import ARC_MESSAGES, FORMAT_VERSION, string_file  # noqa: E402

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LANGUAGES = {"en": 0, "de": 1, "fr": 2, "es": 3, "it": 4}
ENTRY_HEADER = 4
MESSAGE_BYTES = 100


def message(entries, index, language):
    """`JIM::Get_Text_Message_`'s own arithmetic, and its own read."""
    entry = index * 6 + language
    if not 0 <= entry < len(entries):
        raise SystemExit(f"message {index} wants entry {entry} and the "
                         f"file has {len(entries)}")
    blob = bytes(entries[entry])[ENTRY_HEADER:ENTRY_HEADER + MESSAGE_BYTES]
    return blob.split(b"\x00")[0].decode("latin-1")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--lbx", default=os.path.expanduser(
        "~/Master of Orion 2/KENTEXT.LBX"))
    ap.add_argument("--lang", default="en", choices=sorted(LANGUAGES))
    ap.add_argument("--out")
    args = ap.parse_args()
    entries = lbx.read_entries(args.lbx)
    if len(entries) % 6:
        raise SystemExit(f"{args.lbx}: {len(entries)} entries is not a "
                         f"multiple of six, so it is not six per message")
    code = LANGUAGES[args.lang]
    arcs = {str(bit): message(entries, idx, code)
            for bit, idx in sorted(ARC_MESSAGES.items())}
    out = args.out or os.path.join(BASE_DIR, *string_file(args.lang).split("/"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    doc = {
        "_comment": "Generated by tools/kentext_extract.py from the "
                    "player's own KENTEXT.LBX. Never committed "
                    "(decision 38).",
        "_source": "jim.cpp Get_Text_Message_, design.cpp "
                   "Weapon_Arc_String_",
        "language": args.lang,
        "format": FORMAT_VERSION,
        "entries": len(entries),
        "arcs": arcs,
    }
    with open(out, "w", encoding="utf-8") as handle:
        json.dump(doc, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print(f"{len(arcs)} arc words -> {out}")
    for bit, word in sorted(arcs.items(), key=lambda kv: int(kv[0])):
        print(f"   0x{int(bit):02X}  {word!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
