#!/usr/bin/env python3
"""Extract the system-special descriptions from the user's MAINTEXT.LBX.

    python tools/maintext_extract.py
    python tools/maintext_extract.py --lang de --lbx /path/to/MAINGERM.LBX

Output:
    assets/shared/names/maintext_<lang>.json

DERIVED from the user's own MOO2 installation, never committed, never
shipped (decisions 38, 40, 42). `core/maintext.py` reads it and says
"missing" or "stale" rather than guessing.

THE FORMAT, from the reader and not from the file: every entry is a
record array — `uint16 count, uint16 element_size` and the records —
read by `MAINPUPS::System_Special_Desc_` (mainpups.cpp:1065) as record
0 of count 1 and size 600 (0x258). Each record is one NUL-terminated
string in the game's code page. The English file has 14 such entries:
0 "No Special", the eleven system specials, then Trade Goods and
Housing.

THE BYTES ARE HANDED OVER UNTOUCHED: cut at the first NUL, decoded as
code page 437, nothing stripped, joined or reflowed — the help texts'
lesson (decision 38), where a harmless-looking strip ate control codes
the formatter needs. An entry whose header is not a 600-byte record
array is skipped and counted, and a file with none at all writes
nothing.
"""
import argparse
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core import lbx  # noqa: E402
from core import maintext  # noqa: E402
from core.config import BASE_DIR, load_settings  # noqa: E402

INSTALL = os.path.expanduser("~/Master of Orion 2")


def find_lbx(explicit, language):
    """The explicit path, or the language's file in the install, any case."""
    if explicit:
        return explicit if os.path.isfile(explicit) else None
    want = maintext.LBX_BY_LANGUAGE[language]
    if os.path.isdir(INSTALL):
        for name in os.listdir(INSTALL):
            if name.lower() == want:
                return os.path.join(INSTALL, name)
    return None


def parse_entry(blob):
    """The record's text, or None when the entry is not a 600-byte array."""
    if len(blob) < 4:
        return None
    count, size = struct.unpack_from("<HH", blob, 0)
    if count < 1 or size != maintext.RECORD_SIZE or len(blob) < 4 + size:
        return None
    raw = blob[4:4 + size]
    end = raw.find(b"\x00")
    return (raw if end < 0 else raw[:end]).decode("cp437", errors="replace")


def extract(path):
    """({entry: text}, skipped entry count)."""
    entries, skipped = {}, 0
    for index, blob in enumerate(lbx.read_entries(path)):
        text = parse_entry(blob)
        if text is None:
            skipped += 1
        else:
            entries[index] = text
    return entries, skipped


def write(entries, path, language, out_dir):
    target = os.path.join(out_dir, os.path.basename(maintext.text_file(language)))
    os.makedirs(out_dir, exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        json.dump({
            "_comment": ("GENERATED by tools/maintext_extract.py from "
                         f"{os.path.basename(path)}. Derived from the "
                         "user's own MOO2 installation — do not edit, do "
                         "not ship. Regenerate after changing the game "
                         "language."),
            "_source": os.path.basename(path),
            "language": language,
            "format": maintext.FORMAT_VERSION,
            "entries": {str(k): v for k, v in sorted(entries.items())},
        }, handle, ensure_ascii=False, indent=1)
        handle.write("\n")
    return target


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lbx", default=None)
    parser.add_argument("--lang", default=None,
                        help="language code; default: settings.json")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    lang = args.lang or load_settings().get("language", "en")
    if lang not in maintext.LBX_BY_LANGUAGE:
        sys.exit(f"unknown language {lang!r}; known: "
                 f"{sorted(maintext.LBX_BY_LANGUAGE)}")
    path = find_lbx(args.lbx, lang)
    if path is None:
        sys.exit(f"{args.lbx or maintext.LBX_BY_LANGUAGE[lang]} not found. "
                 f"Point --lbx at your own installation's file.")
    entries, skipped = extract(path)
    if not entries:
        sys.exit(f"{path}: no entry is a {maintext.RECORD_SIZE}-byte record "
                 f"array — not a MAINTEXT file; nothing written.")
    target = write(entries, path, lang,
                   args.out or os.path.join(BASE_DIR, "assets", "shared",
                                            "names"))
    print(f"wrote {target}: {len(entries)} descriptions"
          + (f", {skipped} entries skipped" if skipped else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
