#!/usr/bin/env python3
"""The committed STAND-INS the smoke test reads instead of the player's.

    python tools/make_derived_fixtures.py            # rewrite them
    python tools/make_derived_fixtures.py --check    # verify, write nothing

**WHY THESE EXIST.** Four times a smoke check asserted on a catalogue
extracted from the player's own MOO2, passed on the machine that had
run the extractor, and went red in a clone — see the fundament under
Diagnosis, "A check that reads the player's own files passes on the
machine that wrote them". A reminder had already failed to stop the
third one, so the answer is that a check does not get the player's
content: it gets these, which are identical on every machine and are
committed.

**THEY ARE BUILT FROM THE LOADERS' OWN CONSTANTS**, never copied from
a real extraction. `HSTRINGS_COUNT`, `ESTRINGS_COUNT`,
`BUILDING_COUNT`, `SPECIAL_COUNT` and the rest live in `core/`, and
so does each file's `FORMAT_VERSION`. That is what makes this tool
runnable in a clone that has never seen MOO2, and what makes the
stand-in go stale loudly when a format changes rather than quietly:
the same `FORMAT_VERSION` the loader refuses on is the one written
here, and `--check` fails if the two drift.

**THE VALUES ARE DELIBERATELY NOT PLAUSIBLE.** "Weapon 14", not
"Nuclear Missile". A stand-in that reads like real data invites a
check to assert on the wording, which is the player's and is not
ours to pin; and if one ever leaks into a screenshot it says at once
what it is.

They live under `tools/fixtures/derived/` in the SAME relative layout
the loaders use, so the suite reaches them with the loader's own
code path — `HStrings("en", root=DERIVED_ROOT)` and nothing else
changed. A stand-in that bypassed the loader would test nothing.
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from core import billtext, buildnames, estrings, hestrings  # noqa: E402
from core import helptext, kentext, maintext, shipparts  # noqa: E402
from core import infotext, skildesc, technames  # noqa: E402
# THE IDS COME FROM THE RENDERER'S OWN TABLE, not from a second
# list here: `PARAGRAPH_HELP` is what the Fleets panel looks up,
# so a stand-in built from it cannot hold a record the screen
# never asks for, or miss one it does. `fltrows` imports `core`
# only and pulls in no pygame, which is what makes this safe.
from screens.fleets.fltrows import PARAGRAPH_HELP  # noqa: E402

#: Where they go. Named `derived` because that is what the files they
#: stand in for are called everywhere else in the tree.
DERIVED_ROOT = os.path.join(ROOT, "tools", "fixtures", "derived")

#: The comment every stand-in carries, so nobody mistakes one for an
#: extraction while looking at the file itself.
NOTE = ("STAND-IN, generated by tools/make_derived_fixtures.py from "
        "the loader's own constants. NOT extracted from anybody's "
        "MOO2, and not the game's wording. The smoke test reads these "
        "so that a check cannot depend on what this machine has "
        "extracted — see doc/v3_fundament.md, Diagnosis.")


def _numbered(prefix, count):
    """`{index: "Prefix N"}`, the whole range, as the loaders key it."""
    return {str(i): f"{prefix} {i}" for i in range(count)}


def files():
    """`{relative path: document}` for every stand-in."""
    out = {}
    out[hestrings.string_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": hestrings.FORMAT_VERSION,
        "header": {"entries": hestrings.HSTRINGS_COUNT, "bytes": 0},
        # **EVERY ONE CARRIES A `%s`**, because many of the real
        # HESTRNGS entries are format strings — 0x9B is
        # "Destination, %s" — and a stand-in without a placeholder
        # silently drops whatever is substituted into it. Uniform
        # rather than per-index: the stand-in has no business knowing
        # which of its callers formats it, and a caller that does not
        # format simply shows the "%s", which is visibly a stand-in.
        "strings": [f"HE {i} %s" for i in range(hestrings.HSTRINGS_COUNT)],
    }
    out[estrings.string_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": estrings.FORMAT_VERSION,
        "count": estrings.ESTRINGS_COUNT,
        "strings": [f"ES {i}" for i in range(estrings.ESTRINGS_COUNT)],
    }
    out[buildnames.name_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": buildnames.FORMAT_VERSION,
        "buildings": _numbered("Building", buildnames.BUILDING_COUNT),
    }
    out[technames.name_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": technames.FORMAT_VERSION,
        "fields": _numbered("Field", technames.TECH_FIELD_COUNT),
        "applications": _numbered("Application", technames.TECH_APP_COUNT),
    }
    out[shipparts.name_file("en")] = dict(
        {"_comment": NOTE, "language": "en",
         "format": shipparts.FORMAT_VERSION},
        **{key: _numbered(key[:-1].title() if key.endswith("s") else key,
                          count)
           for key, (_first, count) in shipparts.TABLES.items()})
    # Work order 175 D: the Info screen's topic lists, trait names and
    # group names — synthetic, shaped like the real file.
    out[infotext.text_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": infotext.FORMAT_VERSION,
        "topics": {str(e): [[f"Topic {e}-{k}", e * 20 + k] for k in range(3)]
                   for e in range(1, 17)},
        "traits": [f"Trait {i}" for i in range(32)],
        "groups": {str(i): f"Group {i}" for i in range(26)},
    }
    out[kentext.string_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": kentext.FORMAT_VERSION,
        # keyed by the BIT, which is how `ArcWords.arc` looks them up
        "arcs": {str(bit): f"A{bit:02X}"
                 for bit in sorted(kentext.ARC_MESSAGES)},
    }
    out[billtext.message_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": billtext.FORMAT_VERSION,
        "messages": _numbered("Bill", 80),
    }
    out[maintext.text_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": maintext.FORMAT_VERSION,
        "entries": _numbered("Main", 16),
    }
    # THE THREE HELP RECORDS THE FLEETS PANEL PRINTS for a colony ship,
    # a transport and an outpost (work order 159). Only those three:
    # HELP.LBX has hundreds and the right-click popup reads the real
    # file, so a stand-in of the whole catalogue would be a second copy
    # of something nobody checks. `title` is carried because the loader
    # accepts a record without one and the panel prints only `body` —
    # a stand-in whose title were absent could not catch a renderer
    # that started printing it.
    out[helptext.help_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": helptext.FORMAT_VERSION,
        "entries": {str(help_id): {"title": f"Help {help_id} title",
                                   "body": f"Help {help_id} body"}
                    for help_id in sorted(PARAGRAPH_HELP.values())},
    }
    # THE LEADERS SCREEN'S SKILL TEXTS (work order 167). Every
    # description carries the `%s` and the `%d` the original formats
    # into it (officer.cpp:1782), so a stand-in exercises the
    # substitution and not only the lookup.
    out[skildesc.string_file("en")] = {
        "_comment": NOTE, "language": "en",
        "format": skildesc.FORMAT_VERSION,
        "names": [f"SKILL_{i}" for i in range(skildesc.RECORD_COUNT)],
        "descriptions": [f"%s has skill pair {i}, worth %d."
                         for i in range(skildesc.RECORD_COUNT)],
    }
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify what is on disk, write nothing")
    args = ap.parse_args()

    bad = 0
    for rel, doc in sorted(files().items()):
        path = os.path.join(DERIVED_ROOT, *rel.split("/"))
        text = json.dumps(doc, indent=2) + "\n"
        if args.check:
            have = (open(path, encoding="utf-8").read()
                    if os.path.exists(path) else None)
            state = "ok" if have == text else (
                "MISSING" if have is None else "STALE")
            print(f"  {state:8s} {rel}")
            bad += state != "ok"
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"  wrote {rel}")
    if args.check and bad:
        print(f"\n{bad} stand-in(s) out of date — run "
              f"`python tools/make_derived_fixtures.py`")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
