#!/usr/bin/env python3
"""Generate `doc/modding_figures.md` from the loader's own table.

    python tools/make_modding_doc.py            # write it
    python tools/make_modding_doc.py --check    # compare, change nothing

**THE DOCUMENT IS GENERATED BECAUSE IT IS A LIST OF 54 NAMES.** A
hand-written copy of `colonyfigures.all_names()` is wrong within a
month — a race added, a role renamed, a step added to
`zoomtables.FIGURE_STEP` — and a modder following a stale list gets
silence, because a file with a name nothing looks for is
indistinguishable from a file that is not there. A smoke check
regenerates this and compares byte for byte, so the document cannot
drift from the loader without the test going red.

UNLIKE the extracted figures themselves, this file IS committed. It
is derived from OUR OWN code, not from the player's installation, and
a modder must be able to read it without first running an extractor
(decision 40's line is about game data, not about documentation).
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.config import BASE_DIR  # noqa: E402
from screens.colony_summary import colonyfigures as figures  # noqa: E402

DOC = os.path.join("doc", "modding_figures.md")


def render():
    """The whole document, as text."""
    names = figures.all_names()
    steps = figures.STEPS
    master = figures.MASTER_SIZE
    out = [
        "# Modding the population figures",
        "",
        "**GENERATED by `python tools/make_modding_doc.py` from",
        "`screens/colony_summary/colonyfigures.py`. Do not edit — edit",
        "the table there and regenerate. A smoke check compares the two.**",
        "",
        "The colony screens draw one figure per colonist, out of your own",
        "`RACEICON.LBX`. To change one, put a PNG with the right name in",
        "the right folder and restart. That is the whole procedure:",
        "there is no manifest, no index file and no sprite sheet to cut.",
        "",
        "## Where",
        "",
        "```",
        f"mods/my_mod/{figures.FIGURE_DIR}/<name>.png",
        "```",
        "",
        "Every figure resolves on its own, so a mod that supplies one",
        "file changes one figure and the rest stay the game's.",
        "",
        "## What size",
        "",
        f"The master is **{master} x {master}**, which is the size the",
        "game's own sprites are. It is not a convention this project",
        "chose and it is not negotiable: a file of any other size is",
        "**refused**, with a line in the log naming the size it is and",
        "the size it must be, and the original figure is drawn instead.",
        "Nothing is ever stretched to fit — a figure one step out of",
        "line with its neighbours reads as a rendering fault.",
        "",
        "OrionLayer draws the master at an integer step, nearest",
        "neighbour, picked from the window size. You may replace any",
        "step on its own by shipping the file beside the master:",
        "",
        "Where the row band is far from a multiple of the step the",
        "figure is drawn at a FRACTIONAL size, nearest neighbour, and",
        "the sprite it is scaled from is the step BELOW it — so your",
        f"`{figures.step_name('<name>.png', 2)}` is what gets stretched at 2.6x, not the",
        "master. Nothing about the files below changes; the sizes are",
        "still exact and a wrong-sized file is still refused.",
        "",
        "| file | size | used at |",
        "|---|---:|---|",
        f"| `<name>.png` | {master} x {master} | every step, scaled up |",
    ]
    for step in steps:
        size = figures.step_size(step)
        wins = [k for k, v in sorted(_step_table().items()) if v == step]
        out.append(f"| `{figures.step_name('<name>.png', step)}` | "
                   f"{size} x {size} | {', '.join(wins)} |")
    out += [
        "",
        "For one figure at one step the order is",
        "",
        "1. that step's own file, if the mod has one",
        "2. otherwise the mod's master, stepped up",
        "3. otherwise the same two in the base game's own folder",
        "",
        "resolved **inside each mod before moving to the next**, so a",
        "mod that ships only a master beats the base project's step",
        "files. That is what makes a one-file mod work.",
        "",
        "## The names",
        "",
        f"{len(names)} figures. The race keys are the game's own",
        "identifiers and never the translated names, so a mod keeps",
        "working on a German or French install.",
        "",
        "```",
    ]
    for name in names:
        out.append(name)
    out += [
        "```",
        "",
        "`<race>_farmer`, `_worker` and `_scientist` are the three job",
        "figures. `<race>_portrait` is drawn for a **conquered** pop of",
        "that race, whatever job it is doing. `native` and `android`",
        "are drawn for every race, which is why they carry no race key.",
        "",
        "## If nothing changes",
        "",
        "Check the log. A refused file says so by name. A file whose",
        "name is not in the list above is not read at all and says",
        "nothing — that is the one failure this document exists to",
        "prevent, so copy the names from here rather than typing them.",
        "",
    ]
    return "\n".join(out)


def _step_table():
    """Window key -> step, DERIVED from the colony list's own band.

    There is no per-resolution table any more: the list holds ten
    rows, the band is the window divided by ten and the step is the
    largest whose figure fits it (`colonytrack.figure_step`). A
    modder asking "which window gets my @3x file" gets the answer
    from the same arithmetic the screen uses, so the document cannot
    describe a step the screen does not draw — which is what the
    hand-written table did at 2560x1440 until 8 September 2026.
    """
    import pygame
    from core.layout import Layout
    from core import resources
    from screens.colony_summary import colonytrack
    res = resources.init({})
    cfg = res.load_json("screens/colony_summary/layout.json", {}) or {}
    # THE LIST'S RECT COMES FROM THE REFERENCE, not from boxes.json —
    # 12 September 2026. That file carries no rectangle for this
    # screen any more: the fourteen cutouts and the six columns are
    # derived at load by `colonyplates.reseat`, and this asks the same
    # pure function the screen goes through.
    from screens.colony_summary import colonyplates
    lref = res.load_json(
        "screens/colony_summary/layout_reference.json", {}) or {}
    la = colonyplates.all_rects(lref).get("list_area") if lref else None
    if la is None:
        return {}
    out = {}
    # THE SHIPPED RESOLUTIONS and not boxes.json's keys: a box rect is
    # reference space and the fallback chain resolves 3840x2160 to the
    # 1440p list, so that window has no key of its own and would drop
    # out of a table keyed on the file.
    for key in lref.get("_resolutions", ()):
        w, h = (int(v) for v in key.split("x"))
        area = pygame.Rect(*Layout(w, h).rect(la))
        out[key] = colonytrack.figure_step(area, cfg.get("list", {}))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    path = os.path.join(BASE_DIR, *DOC.split("/"))
    text = render()
    if args.check:
        current = (open(path, encoding="utf-8").read()
                   if os.path.exists(path) else "")
        if current == text:
            print(f"{DOC} is current.")
            return 0
        print(f"{DOC} is STALE — run `python tools/make_modding_doc.py`")
        return 1
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote {DOC} ({len(figures.all_names())} figure names)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
