#!/usr/bin/env python3
"""Extract the stock races' traits from the user's installation.

    python tools/racestuf_extract.py
    python tools/racestuf_extract.py --lang de --lbx /path/to/RACESTUF.LBX

**THE HELP-TEXT PATTERN** (decision 38), work order 209 A2: the bytes
are moved out untouched and `core/racestuf.py` builds the list at load
time. RACESTUF.LBX holds every language in one file — the trait records
in entry 7 (racesel.cpp:137-140), the names in entry `language + 8`
(loader.cpp:105-127) — so the language picks an entry, not a file.

**GENERATED, NEVER COMMITTED** (decisions 38, 40, 42) — it is the
user's game data.
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from core import lbx  # noqa: E402
from core import paths  # noqa: E402 — work order 229 D: the game folder
from core.config import BASE_DIR, load_settings  # noqa: E402
from core.racestuf import (  # noqa: E402
    FORMAT_VERSION, NAME_COUNT, NAME_ENTRY, RACE_COUNT, TRAIT_COUNT,
    TRAIT_ENTRY, string_file)

GAME_DIR = paths.game_dir()
LBX_NAME = "RACESTUF.LBX"


def find(folder, filename):
    """The file in `folder`, whatever case the installation uses."""
    if not os.path.isdir(folder):
        return None
    for name in os.listdir(folder):
        if name.lower() == filename.lower():
            return os.path.join(folder, name)
    return None


def records(blob):
    """Entry 7's records, refused unless the header says what the game
    reads: `Far_Reload_Next_Data_(…, 7, …, i, 1, TRAIT_COUNT)`."""
    count = int.from_bytes(blob[0:2], "little")
    size = int.from_bytes(blob[2:4], "little")
    if (count, size) != (RACE_COUNT, TRAIT_COUNT):
        sys.exit(f"entry {TRAIT_ENTRY}: header says {count} records of "
                 f"{size} bytes; the game reads {RACE_COUNT} of "
                 f"{TRAIT_COUNT} (racesel.cpp:137-140)")
    if len(blob) < 4 + count * size:
        sys.exit(f"entry {TRAIT_ENTRY}: {len(blob)} bytes, "
                 f"{4 + count * size} needed")
    # Signed: byte 0 is the government and the bonus levels are small,
    # but the original reads them as int8_t (racesel.cpp:1037).
    return [[b - 256 if b > 127 else b
             for b in blob[4 + i * size: 4 + (i + 1) * size]]
            for i in range(count)]


def names(blob):
    """The names as `Load_Player_Special_Names_` walks them: a string,
    then every NUL after it skipped, 32 times (loader.cpp:113-126)."""
    out, pos = [], 0
    while len(out) < NAME_COUNT:
        end = blob.find(b"\0", pos)
        if end < 0:
            sys.exit(f"the names entry ends after {len(out)} names; the "
                     f"game walks {NAME_COUNT}")
        out.append(blob[pos:end].decode("cp437", errors="replace"))
        pos = end
        while pos < len(blob) and blob[pos] == 0:
            pos += 1
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lbx", default=None)
    parser.add_argument("--lang", default=None,
                        help="language code; default: settings.json")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    lang = args.lang or load_settings().get("language", "en")
    if lang not in NAME_ENTRY:
        sys.exit(f"unknown language {lang!r}; known: {sorted(NAME_ENTRY)}")
    path = args.lbx or find(GAME_DIR, LBX_NAME)
    if not path or not os.path.exists(path):
        sys.exit(f"{LBX_NAME} not found. Point --lbx at your own "
                 f"installation's copy.")
    doc = {
        "_comment": "Generated by tools/racestuf_extract.py from the "
                    "player's own RACESTUF.LBX. Never committed "
                    "(decision 38).",
        "_source": "racesel.cpp:137-140, loader.cpp:105-127",
        "language": lang,
        "format": FORMAT_VERSION,
        "records": records(lbx.read_entry(path, TRAIT_ENTRY)),
        "names": names(lbx.read_entry(path, NAME_ENTRY[lang])),
    }
    out = args.out or os.path.join(BASE_DIR, *string_file(lang).split("/"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as handle:
        json.dump(doc, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print(f"{len(doc['records'])} races, {len(doc['names'])} names -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
