#!/usr/bin/env python3
"""Extract the officer skill help texts from the user's installation.

    python tools/skildesc_extract.py
    python tools/skildesc_extract.py --lang de --lbx /path/to/GERSKLLS.LBX

**THE HELP-TEXT PATTERN** (decision 38): the records are moved out
untouched — each one cut at its first NUL, which is where the C string
the game prints ends, and nothing else: no strip, no cleaning, because
the fundament's FMTPARA lesson is that trailing bytes can carry layout.
`core/skildesc.py` decodes at load time, the file carries a format
version and is never committed, and `setup.py` names this command when
it is absent.

**THE SHAPE IS NOT ESTRINGS'.** SKILDESC.LBX's two entries are arrays of
FIXED records, read one at a time by index
(`Far_Reload_Next_Data_(lbx, entry, seg, i, 1, size)`,
officer.cpp:2800-2810): entry 0, 27 records of 0x26 bytes (names);
entry 1, 27 records of 0xFF bytes (descriptions). Each entry opens with
the same 4-byte (count, size) header ESTRINGS has, and this refuses a
file whose header does not say 27 and the size the game asks for.

**GENERATED, NEVER COMMITTED** (decisions 38, 40, 42) — it is the
user's game data.
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from core import lbx  # noqa: E402
from core.config import BASE_DIR, load_settings  # noqa: E402
from core.skildesc import (  # noqa: E402
    DESCRIPTION_SIZE, FORMAT_VERSION, LANGUAGE_FILES, NAME_SIZE,
    RECORD_COUNT, string_file)

GAME_DIR = os.path.expanduser("~/Master of Orion 2")


def find(folder, filename):
    """The file in `folder`, whatever case the installation uses."""
    if not os.path.isdir(folder):
        return None
    for name in os.listdir(folder):
        if name.lower() == filename.lower():
            return os.path.join(folder, name)
    return None


def records(blob, size, label):
    """The entry's fixed records, each cut at its first NUL."""
    count = int.from_bytes(blob[0:2], "little")
    have = int.from_bytes(blob[2:4], "little")
    if (count, have) != (RECORD_COUNT, size):
        sys.exit(f"{label}: header says {count} records of {have} bytes; "
                 f"the game reads {RECORD_COUNT} of {size} "
                 f"(officer.cpp:2800-2810)")
    if len(blob) < 4 + count * size:
        sys.exit(f"{label}: {len(blob)} bytes, {4 + count * size} needed")
    out = []
    for i in range(count):
        raw = blob[4 + i * size: 4 + (i + 1) * size]
        out.append(raw.split(b"\0", 1)[0].decode("cp437", errors="replace"))
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lbx", default=None)
    parser.add_argument("--lang", default=None,
                        help="language code; default: settings.json")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    lang = args.lang or load_settings().get("language", "en")
    if lang not in LANGUAGE_FILES:
        sys.exit(f"unknown language {lang!r}; known: {sorted(LANGUAGE_FILES)}")
    path = args.lbx or find(GAME_DIR, LANGUAGE_FILES[lang])
    if not path or not os.path.exists(path):
        sys.exit(f"{LANGUAGE_FILES[lang]} not found. Point --lbx at your "
                 f"own installation's copy.")
    names = records(lbx.read_entry(path, 0), NAME_SIZE, "entry 0")
    descriptions = records(lbx.read_entry(path, 1), DESCRIPTION_SIZE,
                           "entry 1")
    out = args.out or os.path.join(BASE_DIR, *string_file(lang).split("/"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    doc = {
        "_comment": "Generated by tools/skildesc_extract.py from the "
                    "player's own " + LANGUAGE_FILES[lang] + ". Never "
                    "committed (decision 38).",
        "_source": "officer.cpp:2795-2811, :3465-3490",
        "language": lang,
        "format": FORMAT_VERSION,
        "names": names,
        "descriptions": descriptions,
    }
    with open(out, "w", encoding="utf-8") as handle:
        json.dump(doc, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print(f"{len(names)} names, {len(descriptions)} descriptions -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
