#!/usr/bin/env python3
"""Extract the Ship Designer's description texts from the user's installation.

    python tools/techdesc_extract.py
    python tools/techdesc_extract.py --lang de --lbx /path/to/GERTECD.LBX

TECHDESC.LBX (or the language's GERTECD / FRETECD / SPATECD / ITATECD):
entry 1, 39 records of 100 bytes — the special systems' descriptions the
designer prints beside each special; entry 3, 40 records of 100 bytes —
the weapon notes its weapon picker prints (design_main.cpp:580-590; the
file by language, design.cpp:1016-1042). Each entry opens with the
(count, size) header, and this refuses a file whose header is not the
count and size the game asks for.

**Decision 38's pattern**, as `tools/skildesc_extract.py`: each record cut
at its first NUL and nothing else; decoded at load time by
`core/techdesc.py`. **GENERATED, NEVER COMMITTED** (decisions 38, 40, 42).
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from core import lbx  # noqa: E402
from core import paths  # noqa: E402 — work order 229 D: the game folder
from core.config import BASE_DIR, load_settings  # noqa: E402
from core.techdesc import (  # noqa: E402
    FORMAT_VERSION, LANGUAGE_FILES, RECORD_SIZE, SPECIAL_COUNT,
    WEAPON_NOTE_COUNT, string_file)

GAME_DIR = paths.game_dir()


def find(folder, filename):
    """The file in `folder`, whatever case the installation uses."""
    if not os.path.isdir(folder):
        return None
    for name in os.listdir(folder):
        if name.lower() == filename.lower():
            return os.path.join(folder, name)
    return None


def records(blob, count_wanted, label):
    """The entry's fixed records, each cut at its first NUL."""
    count = int.from_bytes(blob[0:2], "little")
    size = int.from_bytes(blob[2:4], "little")
    if (count, size) != (count_wanted, RECORD_SIZE):
        sys.exit(f"{label}: header says {count} records of {size} bytes; "
                 f"the game reads {count_wanted} of {RECORD_SIZE} "
                 f"(design_main.cpp:580-590)")
    if len(blob) < 4 + count * size:
        sys.exit(f"{label}: {len(blob)} bytes, {4 + count * size} needed")
    return [blob[4 + i * size:4 + (i + 1) * size].split(b"\0", 1)[0]
            .decode("cp437", errors="replace") for i in range(count)]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lbx", default=None)
    parser.add_argument("--lang", default=None,
                        help="language code; default: settings.json")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()
    lang = args.lang or load_settings().get("language", "en")
    if lang not in LANGUAGE_FILES:
        sys.exit(f"unknown language {lang!r}; known: {sorted(LANGUAGE_FILES)}")
    path = args.lbx or find(GAME_DIR, LANGUAGE_FILES[lang])
    if not path or not os.path.exists(path):
        sys.exit(f"{LANGUAGE_FILES[lang]} not found. Point --lbx at your "
                 f"own installation's copy.")
    specials = records(lbx.read_entry(path, 1), SPECIAL_COUNT, "entry 1")
    notes = records(lbx.read_entry(path, 3), WEAPON_NOTE_COUNT, "entry 3")
    out = args.out or os.path.join(BASE_DIR, *string_file(lang).split("/"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as handle:
        json.dump({"_comment": "Generated by tools/techdesc_extract.py from "
                               "the player's own " + LANGUAGE_FILES[lang]
                               + ". Never committed (decision 38).",
                   "_source": "design_main.cpp:580-590",
                   "language": lang, "format": FORMAT_VERSION,
                   "specials": specials, "weapon_notes": notes},
                  handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print(f"{len(specials)} special descriptions, {len(notes)} weapon notes "
          f"-> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
